//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIUC311Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.Managements = new HashSet<Management>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int rid { get; set; }
        public string rtype { get; set; }
        public string rown { get; set; }
        public string rdesc { get; set; }
        public string rloc { get; set; }
        public System.DateTime rtime { get; set; }
        public string rlat { get; set; }
        public string rlon { get; set; }
        public string racc { get; set; }
        public string rdir { get; set; }
    
        public virtual ICollection<Management> Managements { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
